CREATE TABLE Student(
    ID CHAR(36) PRIMARY KEY,
    FName NVARCHAR(50),
    LName NVARCHAR(50),
    College NVARCHAR(20),
    Age SMALLINT,
    CYear SMALLINT
);

CREATE TABLE Course(
	ID CHAR(36) PRIMARY KEY,
	Name NVARCHAR(20) UNIQUE
);

CREATE TABLE Enrollment(
	ID CHAR(36) PRIMARY KEY,
	StudentID CHAR(36),
	CourseID CHAR(36),
	CONSTRAINT sidfk FOREIGN KEY(StudentID) REFERENCES Student(ID),
	CONSTRAINT cidfk FOREIGN KEY(CourseID) REFERENCES Course(ID)
);
