CREATE TABLE Student(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FName NVARCHAR(50),
	LName NVARCHAR(50),
	College NVARCHAR(20),
	Age SMALLINT,
	CYear SMALLINT,
);

CREATE TABLE Course(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name NVARCHAR(20) UNIQUE,
);

CREATE TABLE Enrollment(
	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	StudentID UNIQUEIDENTIFIER,
	CourseID UNIQUEIDENTIFIER,
	CONSTRAINT sidfk FOREIGN KEY(StudentID) REFERENCES Student(ID),
	CONSTRAINT cidfk FOREIGN KEY(CourseID) REFERENCES Course(ID)
);
