// <auto-generated />
using System;
using Day6.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Day6.Migrations
{
    [DbContext(typeof(TestingContext))]
    partial class TestingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Day6.DAL.CourseDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseName")
                        .HasColumnType("text");

                    b.Property<double>("Ects")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseDbs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d303483-1232-4017-8c8c-8e1ac6cfcbe8"),
                            CourseName = "Programming 1",
                            Ects = 4.5,
                            TeacherId = new Guid("263e12ef-4686-4695-bece-33220222a7f0")
                        },
                        new
                        {
                            Id = new Guid("04dfa922-76cb-460c-91c5-c80cba7a35f3"),
                            CourseName = "Data structures",
                            Ects = 6.0,
                            TeacherId = new Guid("29fcd3e8-b38f-46ea-ac43-aff0eac767f2")
                        },
                        new
                        {
                            Id = new Guid("29706822-8e3d-4e6f-a37e-7bd8e66524df"),
                            CourseName = "Mathematics",
                            Ects = 5.0,
                            TeacherId = new Guid("29fcd3e8-b38f-46ea-ac43-aff0eac767f2")
                        });
                });

            modelBuilder.Entity("Day6.DAL.EnrollmentDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("EnrollmentDb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d5f6f9b-1d6a-4eae-ae66-19001db34817"),
                            CourseId = new Guid("4d303483-1232-4017-8c8c-8e1ac6cfcbe8"),
                            StudentId = new Guid("a4b20494-5489-4eef-ac76-eb30120b7fc5")
                        },
                        new
                        {
                            Id = new Guid("d1db4e93-58ca-453c-8bc5-304aabaca885"),
                            CourseId = new Guid("04dfa922-76cb-460c-91c5-c80cba7a35f3"),
                            StudentId = new Guid("a4b20494-5489-4eef-ac76-eb30120b7fc5")
                        },
                        new
                        {
                            Id = new Guid("c47ac108-4738-401e-99b1-9a228c6eab86"),
                            CourseId = new Guid("29706822-8e3d-4e6f-a37e-7bd8e66524df"),
                            StudentId = new Guid("fdcb6ced-7ccc-4591-8d4a-4deaa35a9d53")
                        },
                        new
                        {
                            Id = new Guid("de4321b3-cdcd-4c58-b6b3-6f58b5108092"),
                            CourseId = new Guid("4d303483-1232-4017-8c8c-8e1ac6cfcbe8"),
                            StudentId = new Guid("873cd274-2499-4c51-9140-630bbda12030")
                        },
                        new
                        {
                            Id = new Guid("0cce2076-068f-4ec2-b101-881cc1fa494f"),
                            CourseId = new Guid("04dfa922-76cb-460c-91c5-c80cba7a35f3"),
                            StudentId = new Guid("873cd274-2499-4c51-9140-630bbda12030")
                        },
                        new
                        {
                            Id = new Guid("aa8c2f58-dfaf-4722-8324-87ebe6113973"),
                            CourseId = new Guid("29706822-8e3d-4e6f-a37e-7bd8e66524df"),
                            StudentId = new Guid("873cd274-2499-4c51-9140-630bbda12030")
                        },
                        new
                        {
                            Id = new Guid("deaad0e9-5833-4447-b16a-1d9a36dedbfd"),
                            CourseId = new Guid("04dfa922-76cb-460c-91c5-c80cba7a35f3"),
                            StudentId = new Guid("51e9879c-7082-4f19-87f9-723c3ba0b56b")
                        });
                });

            modelBuilder.Entity("Day6.DAL.StudentDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentDbs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4b20494-5489-4eef-ac76-eb30120b7fc5"),
                            Age = 21,
                            FirstName = "Peter",
                            LastName = "Johnson",
                            Year = 2
                        },
                        new
                        {
                            Id = new Guid("fdcb6ced-7ccc-4591-8d4a-4deaa35a9d53"),
                            Age = 22,
                            FirstName = "Gregory",
                            LastName = "Armstrong",
                            Year = 2
                        },
                        new
                        {
                            Id = new Guid("873cd274-2499-4c51-9140-630bbda12030"),
                            Age = 20,
                            FirstName = "Poe",
                            LastName = "Wilson",
                            Year = 1
                        },
                        new
                        {
                            Id = new Guid("51e9879c-7082-4f19-87f9-723c3ba0b56b"),
                            Age = 25,
                            FirstName = "Luke",
                            LastName = "Washington",
                            Year = 3
                        });
                });

            modelBuilder.Entity("Day6.DAL.TeacherDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TeacherDbs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29fcd3e8-b38f-46ea-ac43-aff0eac767f2"),
                            Department = "Data visualization",
                            FirstName = "Richard",
                            LastName = "Jameson"
                        },
                        new
                        {
                            Id = new Guid("263e12ef-4686-4695-bece-33220222a7f0"),
                            Department = "Robotics",
                            FirstName = "John",
                            LastName = "Green"
                        });
                });

            modelBuilder.Entity("Day6.DAL.CourseDb", b =>
                {
                    b.HasOne("Day6.DAL.TeacherDb", "TeacherDb")
                        .WithMany("CourseDbs")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherDb");
                });

            modelBuilder.Entity("Day6.DAL.EnrollmentDb", b =>
                {
                    b.HasOne("Day6.DAL.CourseDb", "CourseDb")
                        .WithMany("EnrollmentDbs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day6.DAL.StudentDb", "StudentDb")
                        .WithMany("EnrollmentDbs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseDb");

                    b.Navigation("StudentDb");
                });

            modelBuilder.Entity("Day6.DAL.CourseDb", b =>
                {
                    b.Navigation("EnrollmentDbs");
                });

            modelBuilder.Entity("Day6.DAL.StudentDb", b =>
                {
                    b.Navigation("EnrollmentDbs");
                });

            modelBuilder.Entity("Day6.DAL.TeacherDb", b =>
                {
                    b.Navigation("CourseDbs");
                });
#pragma warning restore 612, 618
        }
    }
}
